version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 9229:9229
      - ${PORT}:${PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:5.0-alpine
    networks:
      - webnet
    ports:
      - 6379:${STORE_PORT}
networks:
  webnet:
